[package]
name = "api_interfaces"
version = "0.1.0"
edition = "2021"

[lib]
name = "api_interfaces"
path = "src/lib.rs"
doctest = false

[dependencies]
reqwest = { version = "0.11", features = ["blocking","json"] }
serde = { version = "1", features = ["derive"] }